PLUGIN_NAME=        inadyn
PLUGIN_VERSION=     0.1
PLUGIN_DEPENDS=     inadyn
PLUGIN_COMMENT=     Internet Automated Dynamic DNS Client
PLUGIN_MAINTAINER=  iain.henderson@mac.com

.include "../../Mk/plugins.mk"
